### ISSUE TITLE
Phantoms arent nerphing in 1.14.4

### ISSUE THREAD

**Issue by FunkyJamma** [Tallcraft/NerfPhantoms#8] opened 2019-07-28 19:31 UTC
I'm having an issue on my server where I get 5 or 6 phantoms spawning in areas with players at once. I tried using this plugin to solve the issues and have played with the values in the config. They don't seem to make a difference. If I type in /nerfphfantom kill they all die so the plugin is running. I do not seem to be getting any errors either. I just ran /nerfphantoms kill on the server a few minutes ago and it killed 15 phantoms I only have 4 people on at the moment.

**Comment by Trikolon** [comment] 2019-08-01 19:26
Phantoms are still spawning naturally, even though you have set `allowNaturalSpawn` to `false`?

**Comment by DatSquidFTW** [comment] 2019-09-25 21:26
I have the same problem on my server. Even with the allowNaturalspawn to false in the config, they still spawn

**Comment by Trikolon** [comment] 2019-12-22 00:44
Can't reproduce your issue. Closing this for now, please reopen if needed.

**Closed by Trikolon** 2019-12-22 00:44 UTC
